### ISSUE TITLE
Unlinked connection when Node is dragged

### ISSUE THREAD

**Issue by aalmiray** [miho/VWorkflows#39]
I've seen this behavior a couple of times already, but can't exactly pinpoint the minimum list of steps to reproduce.

Having a flow with two nodes. The first node has 1 output, the second node has 2 inputs. All data ports are compatible.
Make a connection between output1 and input1.
Make a connection between output1 and input2.
Drag the second node a couple of times.
Click on the first node, then drag the second node again.

Sometimes the second connection (the line) will stay in place while the first connection is dragged correctly when the second node us dragged.

The only way to remove the unlinked connection is to click on the line to bring up the context menu and click on the "remove connection" menu item.

**Comment by miho** [comment]
Should be fixed now. Feel free to reopen the issue if necessary.
