### ISSUE TITLE
net.nemerosa:versioning plugin requires external git client

### ISSUE THREAD

**Issue by miho** [miho/VWorkflows#40]
Currently, the `net.nemerosa:versioning` plugin depends on git/git.exe executables. This is a disadvantage, especially on Windows. For unexperienced users this behavior causes a lot of trouble since most of the time, the git-client provided by the IDE is sufficient and the dependency to an additional git executable complicates the build process.

See https://github.com/nemerosa/versioning/issues/27 for status updates

**Comment by TCMBoby** [comment]
The workaround worked fine.
Had to include Git-Path into environment variables manually to get the project to load otherwise on WIndows 10.

**Comment by dcoraboeuf** [comment]
No dependency on `git` binaries in version 1.7.0. Using JGit/GrGit instead.

**Comment by miho** [comment]
@dcoraboeuf thanks for the fix!
