### ISSUE TITLE
Connectors do not align exactly to the midpoint of an edge

### ISSUE THREAD

**Issue by cbvms123** [miho/VWorkflows#49]
See attached screenshot with background grid.
![alignment](https://cloud.githubusercontent.com/assets/18582202/16831897/d6d5e760-49a7-11e6-8e37-624ef90bc81c.png)

Quick fix on my side was to remove the gap adjustment for the offset[XY] in FXFlowNodeSkin.computeConnector[XY]Value method.

**Comment by miho** [comment]
Wow, that is impossible! It must be an optical illusion :) 

Jokes aside, I can reproduce it. If you have a solution, you are welcome to contribute a patch.
